        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      isrReset ; Reset        ; Int 08h (IRQ 0)
        dd      isrTick ; Tick                ; Int 09h (IRQ 1)
        dd      isrKey ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

	CPU	8086
	align	2

isrReset:
		call ResetHandler

isrKey:

        call save
		call YKEnterISR
		sti
		call KeyHandler
		cli
		call signalEOI
		call YKExitISR
		
		call restore
        iret

isrTick:

        call save
		call YKEnterISR
		sti
		call YKTickHandler
		cli
		call signalEOI
		call YKExitISR
		
		call restore
        iret




; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_myinth_1:
	DW	0
L_myinth_2:
	DB	"RESET ",0
	ALIGN	2
ResetHandler:
	; >>>>> Line:	8
	; >>>>> { 
	jmp	L_myinth_3
L_myinth_4:
	; >>>>> Line:	9
	; >>>>> printString("RESET "); 
	mov	ax, L_myinth_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	10
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_3:
	push	bp
	mov	bp, sp
	jmp	L_myinth_4
L_myinth_7:
	DB	0xA,0
L_myinth_6:
	DB	"TICK ",0
	ALIGN	2
TickHandler:
	; >>>>> Line:	14
	; >>>>> { 
	jmp	L_myinth_8
L_myinth_9:
	; >>>>> Line:	15
	; >>>>> tickCounter++; 
	inc	word [L_myinth_1]
	; >>>>> Line:	16
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	17
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_6
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	18
	; >>>>> printUInt(tickCounter); 
	push	word [L_myinth_1]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	19
	; >>>>> printString("\n"); 
	mov	ax, L_myinth_7
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	20
	; >>>>> YKTickHandler(); 
	call	YKTickHandler
	mov	sp, bp
	pop	bp
	ret
L_myinth_8:
	push	bp
	mov	bp, sp
	jmp	L_myinth_9
	ALIGN	2
L_myinth_11:
	DW	0
L_myinth_15:
	DB	") IGNORED",0xA,0
L_myinth_14:
	DB	"KEYPRESS (",0
L_myinth_13:
	DB	"DELAY COMPLETE",0xA," ",0
L_myinth_12:
	DB	"DELAY KEY PRESSED",0xA," ",0
	ALIGN	2
KeyHandler:
	; >>>>> Line:	24
	; >>>>> { 
	jmp	L_myinth_16
L_myinth_17:
	; >>>>> Line:	26
	; >>>>> if(KeyBuffer == 100) 
	cmp	word [KeyBuffer], 100
	jne	L_myinth_18
	; >>>>> Line:	28
	; >>>>> counter = 0; 
	mov	word [L_myinth_11], 0
	; >>>>> Line:	29
	; >>>>> printString("DELAY KEY PRESSED\n "); 
	mov	ax, L_myinth_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	30
	; >>>>> while(counter < 5000) counter++; 
	jmp	L_myinth_20
L_myinth_19:
	; >>>>> Line:	30
	; >>>>> while(counter < 5000) counter++; 
	inc	word [L_myinth_11]
L_myinth_20:
	cmp	word [L_myinth_11], 5000
	jl	L_myinth_19
L_myinth_21:
	; >>>>> Line:	31
	; >>>>> printString("DELAY COMPLETE\n "); 
	mov	ax, L_myinth_13
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_22
L_myinth_18:
	; >>>>> Line:	35
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_myinth_14
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	36
	; >>>>> printChar(Ke 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> printString(") IGNORED\n"); 
	mov	ax, L_myinth_15
	push	ax
	call	printString
	add	sp, 2
L_myinth_22:
	mov	sp, bp
	pop	bp
	ret
L_myinth_16:
	push	bp
	mov	bp, sp
	jmp	L_myinth_17
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakk.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKCtxSwCount:
	DW	0
i:
	DW	0
hasRun:
	DW	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	42
	; >>>>> { 
	jmp	L_yakk_1
L_yakk_2:
	; >>>>> Line:	43
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	45
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	46
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	48
	; >>>>> YKSave = 0; 
	mov	word [YKSave], 0
	; >>>>> Line:	49
	; >>>>> YKRestore = 0; 
	mov	word [YKRestore], 0
	; >>>>> Line:	50
	; >>>>> YKRdyList = 0; 
	mov	word [YKRdyList], 0
	; >>>>> Line:	51
	; >>>>> YKSuspList = 0; 
	mov	word [YKSuspList], 0
	; >>>>> Line:	52
	; >>>>> YKRunningTask = 0; 
	mov	word [YKRunningTask], 0
	; >>>>> Line:	53
	; >>>>> hasRun = 0; 
	mov	word [hasRun], 0
	; >>>>> Line:	55
	; >>>>> YKAvailTCBList = &(YKTCBArray[0]); 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	59
	; >>>>> for (i = 0; i < 4; i++){ 
	mov	word [i], 0
	jmp	L_yakk_4
L_yakk_3:
	; >>>>> Line:	60
	; >>>>> YKTCBArray[i].next = &(YKTCBArray[i+1]); 
	mov	ax, word [i]
	inc	ax
	mov	cx, 12
	imul	cx
	add	ax, YKTCBArray
	push	ax
	mov	ax, word [i]
	mov	cx, 12
	imul	cx
	mov	dx, ax
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 8
	pop	ax
	mov	word [si], ax
L_yakk_6:
	inc	word [i]
L_yakk_4:
	cmp	word [i], 4
	jl	L_yakk_3
L_yakk_5:
	; >>>>> Line:	65
	; >>>>> YKTCBArray[4].next = 0; 
	mov	word [(56+YKTCBArray)], 0
	; >>>>> Line:	66
	; >>>>> YKTCBArray[4].prev = 0; 
	mov	word [(58+YKTCBArray)], 0
	; >>>>> Line:	68
	; >>>>> YKNewTask(YKIdleTask,(void *) &(idleStk[2048]),100); 
	mov	al, 100
	push	ax
	mov	ax, (idleStk+4096)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakk_1:
	push	bp
	mov	bp, sp
	jmp	L_yakk_2
L_yakk_8:
	DB	"IDLE TASK",0xA,0
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	73
	; >>>>> void YKIdleTask(){ 
	jmp	L_yakk_9
L_yakk_10:
	; >>>>> Line:	74
	; >>>>> printString("IDLE TASK\n"); 
	mov	ax, L_yakk_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	75
	; >>>>> while(1){ 
	jmp	L_yakk_12
L_yakk_11:
	; >>>>> Line:	76
	; >>>>>  
	call	YKEnterMutex
	; >>>>> Line:	77
	; >>>>> YKIdleCount++; 
	inc	word [YKIdleCount]
	; >>>>> Line:	78
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakk_12:
	jmp	L_yakk_11
L_yakk_13:
	mov	sp, bp
	pop	bp
	ret
L_yakk_9:
	push	bp
	mov	bp, sp
	jmp	L_yakk_10
	ALIGN	2
YKScheduler:
	; >>>>> Line:	82
	; >>>>> void YKScheduler(int isSaved){ 
	jmp	L_yakk_15
L_yakk_16:
	; >>>>> Line:	83
	; >>>>> if (YKRunningTask != YKRdyList){ 
	mov	ax, word [YKRdyList]
	cmp	ax, word [YKRunningTask]
	je	L_yakk_17
	; >>>>> Line:	84
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	85
	; >>>>> YKDispatcher(isSaved); 
	push	word [bp+4]
	call	YKDispatcher
	add	sp, 2
L_yakk_17:
	mov	sp, bp
	pop	bp
	ret
L_yakk_15:
	push	bp
	mov	bp, sp
	jmp	L_yakk_16
	ALIGN	2
YKNewTask:
	; >>>>> Line:	90
	; >>>>> { 
	jmp	L_yakk_19
L_yakk_20:
	; >>>>> Line:	94
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	96
	; >>>>> tempPtr0 = YKAvailTCBList; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-4], ax
	; >>>>> Line:	97
	; >>>>> if(tempPtr0 == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakk_21
	; >>>>> Line:	98
	; >>>>> return; 
	jmp	L_yakk_22
L_yakk_21:
	; >>>>> Line:	101
	; >>>>> YKAvailTCBList = tempPtr0->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	; >>>>> Line:	103
	; >>>>> tempPtr0->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-4]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	104
	; >>>>>  
	mov	si, word [bp-4]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	106
	; >>>>> if (YKRdyList == 0) 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakk_23
	; >>>>> Line:	108
	; >>>>> YKRdyList = tempPtr0; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	; >>>>> Line:	109
	; >>>>> tempPtr0->next = 0; 
	mov	si, word [bp-4]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	110
	; >>>>> tempPtr0->prev = 0; 
	mov	si, word [bp-4]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakk_24
L_yakk_23:
	; >>>>> Line:	114
	; >>>>> tempPtr1 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	116
	; >>>>> for (i = 0; i < 4; i ++) 
	mov	word [i], 0
	jmp	L_yakk_26
L_yakk_25:
	; >>>>> Line:	118
	; >>>>> if (tempPtr0->priority < tempPtr1->priority){ 
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-6]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakk_29
	; >>>>> Line:	119
	; >>>>> break; 
	jmp	L_yakk_27
	jmp	L_yakk_30
L_yakk_29:
	; >>>>> Line:	123
	; >>>>> tempPtr1 = tempPtr1->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakk_30:
L_yakk_28:
	inc	word [i]
L_yakk_26:
	cmp	word [i], 4
	jl	L_yakk_25
L_yakk_27:
	; >>>>> Line:	126
	; >>>>> if (tempPtr1->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakk_31
	; >>>>> Line:	127
	; >>>>> YKRdyList = tempPtr0; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakk_32
L_yakk_31:
	; >>>>> Line:	130
	; >>>>> )stack 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakk_32:
	; >>>>> Line:	132
	; >>>>> tempPtr0->prev = tempPtr1->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	133
	; >>>>> tempPtr0->next = tempPtr1; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	134
	; >>>>> tempPtr1->prev = tempPtr0; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakk_24:
	; >>>>> Line:	136
	; >>>>> stackPoint = (unsigned *)taskStack; 
	mov	ax, word [bp+6]
	mov	word [bp-2], ax
	; >>>>> Line:	141
	; >>>>> for (i = 0; i < 13; i++) 
	mov	word [i], 0
	jmp	L_yakk_34
L_yakk_33:
	; >>>>> Line:	143
	; >>>>> if (i == 1){ 
	cmp	word [i], 1
	jne	L_yakk_37
	; >>>>> Line:	144
	; >>>>> stackPoint[0] = 0x0200; 
	mov	si, word [bp-2]
	mov	word [si], 512
	jmp	L_yakk_38
L_yakk_37:
	; >>>>> Line:	146
	; >>>>> else if (i == 3){ 
	cmp	word [i], 3
	jne	L_yakk_39
	; >>>>> Line:	147
	; >>>>> stackPoint[0] = (unsigned)task; 
	mov	si, word [bp-2]
	mov	ax, word [bp+4]
	mov	word [si], ax
	jmp	L_yakk_40
L_yakk_39:
	; >>>>> Line:	150
	; >>>>> stackPoint[0] = 0; 
	mov	si, word [bp-2]
	mov	word [si], 0
L_yakk_40:
L_yakk_38:
	; >>>>> Line:	152
	; >>>>> stackPoint--; 
	sub	word [bp-2], 2
L_yakk_36:
	inc	word [i]
L_yakk_34:
	cmp	word [i], 13
	jl	L_yakk_33
L_yakk_35:
	; >>>>> Line:	155
	; >>>>> tempPtr0->stackptr = (void *)stack 
	mov	si, word [bp-4]
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	157
	; >>>>> if(hasRun == 1) { 
	cmp	word [hasRun], 1
	jne	L_yakk_41
	; >>>>> Line:	158
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	159
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakk_41:
L_yakk_22:
	mov	sp, bp
	pop	bp
	ret
L_yakk_19:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakk_20
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	166
	; >>>>> void YKDelayTask(unsigned count){ 
	jmp	L_yakk_43
L_yakk_44:
	; >>>>> Line:	172
	; >>>>> if(count == 0){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakk_45
	; >>>>> Line:	173
	; >>>>> return; 
	jmp	L_yakk_46
L_yakk_45:
	; >>>>> Line:	175
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	177
	; >>>>> tempPtr0 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	178
	; >>>>> tempPtr0->delay = count; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	181
	; >>>>> tempPtr1 = YKSuspList; 
	mov	ax, word [YKSuspList]
	mov	word [bp-4], ax
	; >>>>> Line:	183
	; >>>>> tempPtr2 = YKRdyList->next; 
	mov	si, word [YKRdyList]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
	; >>>>> Line:	186
	; >>>>> if (YKSuspList == 0) 
	mov	ax, word [YKSuspList]
	test	ax, ax
	jne	L_yakk_47
	; >>>>> Line:	188
	; >>>>> YKSuspList = tempPtr0; 
	mov	ax, word [bp-2]
	mov	word [YKSuspList], ax
	; >>>>> Line:	189
	; >>>>> tempPtr0->next = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	190
	; >>>>> tempPtr0->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakk_48
L_yakk_47:
	; >>>>> Line:	194
	; >>>>> while(tempPtr1->next != 0) 
	jmp	L_yakk_50
L_yakk_49:
	; >>>>> Line:	196
	; >>>>> tempPtr1 = t 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakk_50:
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakk_49
L_yakk_51:
	; >>>>> Line:	198
	; >>>>> tempPtr1->next = tempPtr0; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	199
	; >>>>> tempPtr1->next->prev = tempPtr1; 
	mov	si, word [bp-4]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	200
	; >>>>> tempPtr1->next->next = 0; 
	mov	si, word [bp-4]
	add	si, 8
	mov	si, word [si]
	add	si, 8
	mov	word [si], 0
L_yakk_48:
	; >>>>> Line:	203
	; >>>>> tempPtr2->prev = 0; 
	mov	si, word [bp-6]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	204
	; >>>>> YKRdyList = tempPtr2; 
	mov	ax, word [bp-6]
	mov	word [YKRdyList], ax
	; >>>>> Line:	207
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	208
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakk_46:
	mov	sp, bp
	pop	bp
	ret
L_yakk_43:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakk_44
L_yakk_54:
	DB	0xA,0xD,0
L_yakk_53:
	DB	"TICK: ",0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	217
	; >>>>> { 
	jmp	L_yakk_55
L_yakk_56:
	; >>>>> Line:	219
	; >>>>> YKTickNum++; 
	inc	word [YKTickNum]
	; >>>>> Line:	221
	; >>>>> printString("\n"); 
	mov	ax, (L_yakk_8+9)
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	222
	; >>>>> printString("TICK: "); 
	mov	ax, L_yakk_53
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	223
	; >>>>> printInt(YKTickNum); 
	push	word [YKTickNum]
	call	printInt
	add	sp, 2
	; >>>>> Line:	224
	; >>>>> printString("\n\r"); 
	mov	ax, L_yakk_54
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	226
	; >>>>> temp = YKSuspList; 
	mov	ax, word [YKSuspList]
	mov	word [bp-2], ax
	; >>>>> Line:	227
	; >>>>> while (temp != 0) 
	jmp	L_yakk_58
L_yakk_57:
	; >>>>> Line:	229
	; >>>>> temp->delay--; 
	mov	si, word [bp-2]
	add	si, 6
	dec	word [si]
	; >>>>> Line:	230
	; >>>>> if (temp->delay == 0) 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakk_60
	; >>>>> Line:	232
	; >>>>> taskHold = temp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	233
	; >>>>> if (temp 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	je	L_yakk_61
	; >>>>> Line:	235
	; >>>>> temp->prev->next = temp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	di, word [bp-2]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
	jmp	L_yakk_62
L_yakk_61:
	; >>>>> Line:	238
	; >>>>> YKSuspList = temp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKSuspList], ax
L_yakk_62:
	; >>>>> Line:	240
	; >>>>> if (temp->next != 0) 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakk_63
	; >>>>> Line:	242
	; >>>>> temp->next->prev = temp->prev; 
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakk_63:
	; >>>>> Line:	244
	; >>>>> comparisonPoint = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	252
	; >>>>> for (i = 0; i < 4; i ++) 
	mov	word [i], 0
	jmp	L_yakk_65
L_yakk_64:
	; >>>>> Line:	254
	; >>>>> if (temp->priority < comparisonPoint->priority){ 
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-6]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakk_68
	; >>>>> Line:	256
	; >>>>> break; 
	jmp	L_yakk_66
	jmp	L_yakk_69
L_yakk_68:
	; >>>>> Line:	260
	; >>>>> comparisonPoint = comparisonPoint->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakk_69:
L_yakk_67:
	inc	word [i]
L_yakk_65:
	cmp	word [i], 4
	jl	L_yakk_64
L_yakk_66:
	; >>>>> Line:	263
	; >>>>> if (comparisonPoint->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakk_70
	; >>>>> Line:	267
	; >>>>> YKRdyList = temp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakk_71
L_yakk_70:
	; >>>>> Line:	271
	; >>>>> comparisonPoint->prev->next = 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakk_71:
	; >>>>> Line:	275
	; >>>>> temp->prev = comparisonPoint->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	276
	; >>>>> temp->next = comparisonPoint; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	277
	; >>>>> comparisonPoint->prev = temp; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	278
	; >>>>> temp = taskHold; 
	mov	ax, word [bp-4]
	mov	word [bp-2], ax
	jmp	L_yakk_72
L_yakk_60:
	; >>>>> Line:	281
	; >>>>> temp = temp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakk_72:
L_yakk_58:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakk_57
L_yakk_59:
	mov	sp, bp
	pop	bp
	ret
L_yakk_55:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakk_56
	ALIGN	2
YKRun:
	; >>>>> Line:	287
	; >>>>> void YKRun(void){ 
	jmp	L_yakk_74
L_yakk_75:
	; >>>>> Line:	288
	; >>>>> hasRun = 1; 
	mov	word [hasRun], 1
	; >>>>> Line:	289
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakk_74:
	push	bp
	mov	bp, sp
	jmp	L_yakk_75
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	293
	; >>>>> void YKEnterISR(void){ 
	jmp	L_yakk_77
L_yakk_78:
	; >>>>> Line:	295
	; >>>>> YKISRDepth++; 
	inc	word [YKISRDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakk_77:
	push	bp
	mov	bp, sp
	jmp	L_yakk_78
	ALIGN	2
YKExitISR:
	; >>>>> Line:	299
	; >>>>> void YKExitISR(void){ 
	jmp	L_yakk_80
L_yakk_81:
	; >>>>> Line:	301
	; >>>>> YKISRDepth--; 
	dec	word [YKISRDepth]
	; >>>>> Line:	303
	; >>>>> if(YKISRDepth == 0) { 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakk_82
	; >>>>> Line:	304
	; >>>>> if(hasRun == 1) 
	cmp	word [hasRun], 1
	jne	L_yakk_83
	; >>>>> Line:	306
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakk_83:
L_yakk_82:
	mov	sp, bp
	pop	bp
	ret
L_yakk_80:
	push	bp
	mov	bp, sp
	jmp	L_yakk_81
	ALIGN	2
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKISRDepth:
	TIMES	2 db 0
YKSave:
	TIMES	2 db 0
YKRestore:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKSuspList:
	TIMES	2 db 0
YKRunningTask:
	TIMES	2 db 0
YKTCBArray:
	TIMES	60 db 0
idleStk:
	TIMES	4096 db 0
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4c.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4c_2:
	DB	"Starting kernel...",0xA,0
L_lab4c_1:
	DB	"Creating tasks...",0xA,0
	ALIGN	2
main:
	; >>>>> Line:	26
	; >>>>> { 
	jmp	L_lab4c_3
L_lab4c_4:
	; >>>>> Line:	27
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	29
	; >>>>> printString("Creating tasks...\n"); 
	mov	ax, L_lab4c_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	30
	; >>>>> YKNewTask(ATask, (void *) &AStk[256], 3); 
	mov	al, 3
	push	ax
	mov	ax, (AStk+512)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	31
	; >>>>> YKNewTask(BTask, (void *) &BStk[256], 5); 
	mov	al, 5
	push	ax
	mov	ax, (BStk+512)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	32
	; >>>>> YKNewTask(CTask, (void *) &CStk[256], 7); 
	mov	al, 7
	push	ax
	mov	ax, (CStk+512)
	push	ax
	mov	ax, CTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	33
	; >>>>> YKNewTask(DTask, (void *) &DStk[256], 8); 
	mov	al, 8
	push	ax
	mov	ax, (DStk+512)
	push	ax
	mov	ax, DTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	35
	; >>>>> printString("Starting kernel...\n"); 
	mov	ax, L_lab4c_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	36
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4c_3:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_4
L_lab4c_7:
	DB	"Task A, delaying 2.",0xA,0
L_lab4c_6:
	DB	"Task A started.",0xA,0
	ALIGN	2
ATask:
	; >>>>> Line:	40
	; >>>>> { 
	jmp	L_lab4c_8
L_lab4c_9:
	; >>>>> Line:	41
	; >>>>> printString("Task A starte 
	mov	ax, L_lab4c_6
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	42
	; >>>>> while (1) 
	jmp	L_lab4c_11
L_lab4c_10:
	; >>>>> Line:	44
	; >>>>> printString("Task A, delaying 2.\n"); 
	mov	ax, L_lab4c_7
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	45
	; >>>>> YKDelayTask(2); 
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4c_11:
	jmp	L_lab4c_10
L_lab4c_12:
	mov	sp, bp
	pop	bp
	ret
L_lab4c_8:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_9
L_lab4c_15:
	DB	"Task B, delaying 3.",0xA,0
L_lab4c_14:
	DB	"Task B started.",0xA,0
	ALIGN	2
BTask:
	; >>>>> Line:	50
	; >>>>> { 
	jmp	L_lab4c_16
L_lab4c_17:
	; >>>>> Line:	51
	; >>>>> printString("Task B started.\n"); 
	mov	ax, L_lab4c_14
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	52
	; >>>>> while (1) 
	jmp	L_lab4c_19
L_lab4c_18:
	; >>>>> Line:	54
	; >>>>> printString("Task B, delaying 3.\n"); 
	mov	ax, L_lab4c_15
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	55
	; >>>>> YKDelayTask(3); 
	mov	ax, 3
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4c_19:
	jmp	L_lab4c_18
L_lab4c_20:
	mov	sp, bp
	pop	bp
	ret
L_lab4c_16:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_17
L_lab4c_23:
	DB	"Task C, delaying 5.",0xA,0
L_lab4c_22:
	DB	"Task C started.",0xA,0
	ALIGN	2
CTask:
	; >>>>> Line:	60
	; >>>>> { 
	jmp	L_lab4c_24
L_lab4c_25:
	; >>>>> Line:	61
	; >>>>> printString("Task C started.\n"); 
	mov	ax, L_lab4c_22
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	62
	; >>>>> while (1) 
	jmp	L_lab4c_27
L_lab4c_26:
	; >>>>> Line:	64
	; >>>>> printString("Task C, delaying 5.\n"); 
	mov	ax, L_lab4c_23
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	65
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4c_27:
	jmp	L_lab4c_26
L_lab4c_28:
	mov	sp, bp
	pop	bp
	ret
L_lab4c_24:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_25
L_lab4c_31:
	DB	"Task D, delaying 10.",0xA,0
L_lab4c_30:
	DB	"Task D started.",0xA,0
	ALIGN	2
DTask:
	; >>>>> Line:	70
	; >>>>> { 
	jmp	L_lab4c_32
L_lab4c_33:
	; >>>>> Line:	71
	; >>>>> printString("Task D started.\n"); 
	mov	ax, L_lab4c_30
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	72
	; >>>>> while (1) 
	jmp	L_lab4c_35
L_lab4c_34:
	; >>>>> Line:	74
	; >>>>> printStr 
	mov	ax, L_lab4c_31
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	75
	; >>>>> YKDelayTask(10); 
	mov	ax, 10
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab4c_35:
	jmp	L_lab4c_34
L_lab4c_36:
	mov	sp, bp
	pop	bp
	ret
L_lab4c_32:
	push	bp
	mov	bp, sp
	jmp	L_lab4c_33
	ALIGN	2
AStk:
	TIMES	512 db 0
BStk:
	TIMES	512 db 0
CStk:
	TIMES	512 db 0
DStk:
	TIMES	512 db 0

YKEnterMutex:
	cli			;Disable interrupts
	ret

YKExitMutex:
	sti			;Enable interrupts
	ret

save:
				;Save the context of the current task. 9 total
	push	ax
	push	bx
	push	cx
	push	dx
	push	es
	push	ds
	push 	si
	push	di
	push 	bp
				;Return address must be placed on top of the stack
				;Move 9 words up the stack
	mov		bp, sp 			;Move stack pointer
	push	word[bp+18]		;Go to the top of the stack
	mov		[bp+18], cx		;Keep track of cx

	mov cx, [YKISRDepth]
	cmp cx, 0				;Compare the ISRDepth with 0. This will perform (ISRDepth-0)
	jg return				;if (ISRDepth-0) is greater than 0, we need to return.
							;If the ISRDepth is 0, it will skip the return

	mov bx, [YKRunningTask]	;Grab the currently running task
	mov bp, sp				
	add	bp, 2
	mov [bx], bp

return:
	ret

YKDispatcher:
	
	push bp 	
	mov bp, sp	
	cmp	byte[bp+4], 1		; compare the argument with 1 
	pop bp
	je	dispatcherRestore 	;if the argument is 1, restore old saved context
	push cs					
	pushf					;Push flag register onto stack
	call save				;Save the new context
	mov	bp, sp				;Move stack pointer to bp
	mov	bx, [bp+20]			;Store the task
	mov	ax, [bp+24]			;Store the interrupt flag
	mov	[bp+20], ax			;Set the task	
	or bx, 0x0200			;or flag with 0x0200
	mov	[bp+24], bx			;Move flag to flag position

dispatcherRestore:			;If not saved, restore the old context
	mov bx, [YKRdyList]		;store the new task
	mov sp, [bx]			;Store saved bp
	mov	[YKRunningTask], bx	;Grab the currently running task. to restore content
	call restore			;Restore the content of the running task
	iret					;iret to restore context not restored already

restore:					;Restore context
	
	mov	bp, sp
	mov cx, [bp+20]
	pop	word[bp+20]
	pop		bp
	pop		di
	pop		si
	pop		ds
	pop		es
	pop		dx
	pop		cx
	pop		bx
	pop		ax
	ret

